# lampstack based on CentOS 7 equipped with MariaDB image detached
#
version: '2.3'
services:
   db:
        image: mariadb:latest
        container_name: mariadb
        volumes:
         - ./mysql:/var/lib/mysql:cached
         - ./mysql-dump:/tmp2
         - ./docker-config/mariadb/script:/docker-entrypoint-initdb.d
         - ./docker-config/mariadb/config:/etc/mysql/conf.d
         - ./mysql-cron:/usr/local/sbin
        environment:
         - MARIADB_ROOT_PASSWORD=db_root_password
         - MARIADB_DB=projeqtr
         - MARIADB_USER=projeqtor
         - MARIA_PASSWORD=db_projeqtor_password
        networks:
         - projeqtor
        restart: always

   www:
        build:
          context: ./docker-config/centos
        container_name: centos7
        volumes:
         - ./www:/var/www/html
         - ./projeqtor-config:/var/www/html/files/config
         - ./projector-logs:/var/www/html/files/logs
         - ./www-logs:/var/log/httpd
         - ./www-cron:/usr/local/sbin
        networks:
         - projeqtor
        ports:
         - "8080:8080"
        restart: always
        depends_on:
         - db

   backup:
        build:
          context: ./docker-config/centos-rclone
        container_name: centos7-rclone
        volumes:
         - ./rclone-config:/home/root/.rclone
         - ./rclone-logs:/var/log/rclone
         - ./mysql-dump:/mnt/mysql-dump
         - ./projeqtor-config:/mnt/projeqtor-config
         - ./projeqtor-logs:/mnt/projeqtor-logs
         - ./www:/mnt/www
         - ./www-logs:/mnt/www-logs
         - ./rclone-cron:/usr/local/sbin
        restart: always
        networks:
         - projeqtor
        depends_on:
         - db
         - www

networks:
    projeqtor:
        # use the bridge driver, but disable IPv6
        driver: bridge
        internal: false
        driver_opts:
          com.docker.network.enable_ipv6: "false"
        ipam:
          driver: default
          config:
            - subnet: 175.22.0.0/24
              gateway: 175.22.0.1

